### PR TITLE
Features/input focus bug and some general corrections

### PR DESCRIPTION
**Pull request by marcin10lw**

### CODE REVIEW

**Review by HelkaPL — APPROVED** [review]
Seems to be right. Good job :)

**Comment by mikolajgraczyk** [comment]
Also add `id={movie.id}` to ActorPage/Crew for MovieTIle and change header color to black on mobile view 😃

**Review by mikolajgraczyk — CHANGES_REQUESTED** [review]
Also add `id={movie.id}` to ActorPage/Crew for MovieTIle and change header color to black on mobile view 😃

**Comment by marcin10lw** [comment]
@mikolajgraczyk Glad You saw that!

**Review by mikolajgraczyk — APPROVED** [review]
splendid 🤩

**Pull request merged**
