### PR TITLE
Features/searching stuff

### PR DESCRIPTION
**Pull request by HelkaPL**
Ok, so I try to make our SearchBarInput to make some action..
And thats, what I done so far...

Placeholder is now changeing depends on page ( movie || people )

inputValue create searchParams in URL.

### CODE REVIEW

**Review by marcin10lw — COMMENTED** [review]
You did an amazing job here! 💪
We decided to use react-router v6 to make our lives easier and we can simplify our code to look like this: 
image
With that we don't need to use anything from queryParameters custom hook except `searchQueryParamName`
It's up to you which version we will work with

**Comment by HelkaPL** [comment]
> You did an amazing job here! 💪 We decided to use react-router v6 to make our lives easier and we can simplify our code to look like this: image With that we don't need to use anything from queryParameters custom hook except `searchQueryParamName` It's up to you which version we will work with


You are right. I forgot we implemented v6 version ( i still try to catch up witch changes in new version ).

**Review by mikolajgraczyk — APPROVED** [review]
It is surely a step forward working movies search ability 🤩

**Review by marcin10lw — APPROVED** [review]
Love it

**Pull request merged**
